version: "3.8"


services:
 app:
   build: .
   container_name: laravel_app
   ports:
     - "8000:8000"
   volumes:
     - .:/var/www/html
     - /var/www/html/vendor # Prevents overriding vendor folder
   environment:
     - DB_CONNECTION=sqlite
     - DB_DATABASE=/var/www/html/database/database.sqlite



